packages:
  - "app"
  - "lib/*"
  - "web"
catalog:
  "@eslint/js": ^9.27.0
  "@mjackson/node-fetch-server": ^0.6.1
  "@netlify/functions": ^3.1.8
  "@next/eslint-plugin-next": ^15.3.2
  "@react-router/dev": ^7.6.0
  "@react-router/node": ^7.6.0
  "@tailwindcss/vite": ^4.1.7
  "@types/express": ^5.0.2
  "@tauri-apps/api": ^2.5.0
  "@tauri-apps/cli": ^2.5.0
  "@tauri-apps/plugin-opener": ^2.2.7
  "@types/react-dom": ^19.1.5
  "@types/react": ^19.1.5
  "@vitejs/plugin-react": ^4.4.1
  cross-env: ^7.0.3
  eslint-config-prettier: ^10.1.5
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-turbo: ^2.5.3
  eslint: ^9.27.0
  express: ^5.1.0
  globals: ^16.1.0
  husky: ^9.1.7
  isbot: ^5.1.28
  lint-staged: ^16.0.0
  netlify-cli: ^21.5.0
  npm-run-all2: ^8.0.3
  prettier-plugin-sort-package-json: ^0.2.0
  prettier: ^3.5.3
  react-dom: ^19.1.0
  react-router: ^7.6.0
  react: ^19.1.0
  stylelint: ^16.19.1
  stylelint-config-standard: ^38.0.0
  stylelint-config-tailwindcss: ^1.0.0
  stylelint-selector-bem-pattern: ^4.0.1
  tailwindcss: ^4.1.7
  turbo: ^2.5.3
  typescript-eslint: ^8.32.1
  typescript: ^5.8.3
  vite-tsconfig-paths: ^5.1.4
  vite: ^6.3.5
peerDependencyRules:
  allowAny:
    - "@types/express"
